config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cart#products'

  namespace :admin do
    resources :orders, only: [:index]
  end

  namespace :customer do
    resources :orders, only: [:index]
  end

  resources :orders, only: [:show, :create] do
    member do
      put 'cancel'
      put 'finish'
      get 'resume'
      get 'checkout'
      put 'coupon'
    end
  end

  #namespace :cart do
  resource :cart, only: [] do
      get 'products', to: 'cart#products'
      get ':product/:product_id/plans', to: 'cart#plans', as: 'product_plans'
      get ':product/:product_id/:plan/:plan_id/prices', to: 'cart#prices', as: 'plan_prices'
  end

  resources :payments, only: [:create]
  resources :sellers, only: [:new, :create]

  namespace :seller do
    get '/:id/checkout', to: 'orders#checkout', as: 'checkout'
    post 'send/order/:id', to: 'orders#send_order', as: 'send_order'
  end

  resources :payments, only: [:create]
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :set_menus
  before_action :redirect_admin

  def plans
    @product = Product.find(params[:product_id])
    @plans = @product.plans
  end

  def prices
    @product = Product.find params[:product_id]
    @plan = Plan.find params[:plan_id]
    @periodicities = @plan.periodicities
  end

  def products
    @products = Product.all
  end
end

app/views/cart/plans.html.erb
<%= content_for :header_title do %>
  Contratar Produto
<% end %>

<%= content_for :page_title do %>
  Planos para <%= @product.name %>
<% end %>

<ol class="ls-breadcrumb">
  <li>
    <%= link_to @product.name, products_cart_path %>
  </li>
  <li>Planos</li>
</ol>

</br>

<section class="product" id="plans">
  <% @plans.each do |plan| %>
    <%= render partial: 'plans/plan', locals: {plan: plan} %>
  <% end %>
</section>

app/views/cart/prices.html.erb
<%= content_for :header_title do %>
  Periodicidade
<% end %>

<%= content_for :page_title do %>
  Periodos do plano <%= @plan.name %>
<% end %>

<ol class="ls-breadcrumb">
  <li>
    <%= link_to @product.name, products_cart_path %>
  </li>
  <li><%= link_to @plan.name, product_plans_cart_path(@product.name, @product.id) %></li>
  <li>Periodicidade</li>
</ol>

</br>
<section id="prices">
  <% @periodicities.each do |periodicity| %>
    <%= render partial: 'periodicities/periodicity', locals: {periodicity: periodicity} %>
  <% end %>
</section>

app/views/cart/products.html.erb
<% content_for :header_title do %>
  Produtos
<% end %>
<% content_for :page_title do %>
  Nossos produtos
<% end %>
<section id="products">
<% @products.each do |product| %>
  <%= render partial: 'products/product', locals: {product: product} %>
<% end %>
</section>