config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cart#products'

  namespace :admin do
    resources :orders, only: [:index]
  end

  namespace :customer do
    resources :orders, only: [:index]
  end

  resources :orders, only: [:show, :create] do
    member do
      put 'cancel'
      put 'finish'
      get 'resume'
      get 'checkout'
      put 'coupon'
    end
  end

  #namespace :cart do
  resource :cart, only: [] do
      get 'products', to: 'cart#products'
      get ':product/:product_id/plans', to: 'cart#plans', as: 'product_plans'
      get ':product/:product_id/:plan/:plan_id/prices', to: 'cart#prices', as: 'plan_prices'
  end

  resources :payments, only: [:create]
  resources :sellers, only: [:new, :create]

  namespace :seller do
    get '/:id/checkout', to: 'orders#checkout', as: 'checkout'
    post 'send/order/:id', to: 'orders#send_order', as: 'send_order'
  end

  resources :payments, only: [:create]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :seller, class_name: User, optional: true
  has_one :payment

  before_create :set_default_status

  enum status: [:opened, :closed, :canceled]

  def self.statuses_attributes
    statuses.keys.map do |status|
      { value: I18n.t("activerecord.attributes.order.statuses.#{status}"),
        key: status }
    end
  end

  def apply_coupon(informed_coupon)
    self.coupon = informed_coupon.key
    self.price = if informed_coupon.type.eql? 'fixed'
                   price - informed_coupon.value
                 else
                   price * calculate_percent(informed_coupon.value)
                 end
    self.price = 0 if price.negative?
    save
  end

  def check_integrity?(request_ip, request_user)
    if user.nil? && source_ip == request_ip
      update(user: request_user)
      true
    elsif user.nil? && source_ip != request_ip
      false
    else
      valid_user?(request_user)
    end
  end

  def valid_user?(request_user)
    user == request_user
  end

  private

  def set_default_status
    self.status ||= :opened
  end

  def calculate_percent(percent)
    (1 - (percent / 100.0))
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < ApplicationController
    before_action :require_admin
    before_action :set_menus, only: [:index]

    def index
      @statuses = Order.statuses_attributes
      @orders = Order.all
      @current_filter = params[:filter]
      @orders = @orders.where(status: @current_filter) if @current_filter
      flash.now[:info] = 'Não foram encontrados pedidos' if @orders.empty?
    end

    private

    def require_admin
      redirect_to root_path unless current_user.try(:admin?)
    end
  end
end

app/controllers/customer/orders_controller.rb
module Customer
  class OrdersController < ApplicationController
    before_action :require_customer
    before_action :set_menus, only: [:index]

    def index
      @statuses = Order.statuses_attributes
      @orders = current_user.orders.all
      @current_filter = params[:filter]
      @orders = @orders.where(status: @current_filter) if @current_filter
      flash.now[:info] = 'Não foram encontrados pedidos' if @orders.empty?
    end

    private

    def require_customer
      redirect_to root_path unless current_user.try(:customer?)
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  API_URL = Rails.configuration.api['products_api'].freeze
  before_action :set_menus, only: [:show, :checkout, :resume]
  before_action :authenticate_user!, except: [:create, :checkout]
  before_action :authenticate_user_to_order!, except: [:create, :checkout]
  before_action :authenticate_user_to_checkout, only: [:checkout]
  before_action :set_order_attributes, only: [:resume, :show]
  before_action :redirect_admin, except: [:show, :cancel]

  def create
    if valid_params?
      @order = Order.new(order_params)
      define_user_and_seller
      @order.save

      check_redirect_path

    else
      flash[:danger] = 'Pedido não pode ser gerado'
      redirect_to root_path
    end
  end

  def coupon
    coupon = Coupon.apply_coupon(params[:coupon], @order)

    if coupon
      @order.apply_coupon coupon
      flash[:success] = 'Cupom aplicado com sucesso'
    else
      flash[:danger] = 'Cupom inválido'
    end

    redirect_to checkout_order_path @order
  end

  def show; end

  def cancel
    @order.canceled!
    flash[:success] = 'Pedido cancelado com sucesso'
    redirect_to @order
  end

  def finish
    @order.closed!
    flash[:success] = 'Pedido finalizado com sucesso'
    redirect_to @order
  end

  def resume
    redirect_to @order unless @order.opened?
  end

  def checkout
    check_integrity_order
    @credit = Credit.new
    @payment = Payment.new
  end

  private

  def define_user_and_seller
    current_user.orders << @order if user_signed_in? && current_user.customer?
    @order.seller = current_user if user_signed_in? && current_user.seller?
  end

  def check_redirect_path
    if user_signed_in? && current_user.seller?
      redirect_to seller_checkout_path @order
    else
      redirect_to checkout_order_path @order
    end
  end

  def set_order_attributes
    @order = Order.find params[:id]
    @product = Product.find @order.product
    @plan = Plan.find @order.plan
  end

  def valid_params?
    return false unless params.key?(:price_id)
    response = RestClient.get("#{API_URL}/prices/#{params[:price_id]}")
    return false if response.code != 200

    price = JSON.parse(response.body)

    price['price']['product_id'] == params[:product].to_i &&
      price['price']['plan_id'] == params[:plan].to_i &&
      price['price']['value'] == params[:price]
  end

  def order_params
    { product: params[:product], plan: params[:plan], price: params[:price],
      period: params[:period], source_ip: request.remote_ip, status: 'opened' }
  end

  def authenticate_user_to_order!
    @order = Order.find params[:id]
    return if @order.valid_user?(current_user) || current_user.admin?
    flash[:danger] = 'Não foi possível concluir a operação.'
    redirect_to root_path
  end

  def authenticate_user_to_checkout
    set_order_attributes
    return if user_signed_in?
    flash[:info] = 'Para continuar o checkout do pedido' \
      "#{@order.id} faça login ou registre-se"
    redirect_to new_user_session_path
  end

  def check_integrity_order
    return if @order.check_integrity?(request.remote_ip, current_user)
    flash[:danger] = 'Não foi possível concluir a operação.'
    redirect_to root_path
  end
end

app/controllers/seller/orders_controller.rb
module Seller
  class OrdersController < ApplicationController
    before_action :set_menus, except: [:send_order]
    before_action :authenticate_user!

    def checkout
      @order = Order.find params[:id]

      redirect_to root_path unless @order.seller == current_user
      @product = Product.find @order.product
      @plan = Plan.find @order.plan
      @customers = User.customer
    end

    def send_order
      order = Order.find params[:id]
      order.user = User.find params[:order][:user_id]
      order.save
      OrdersMailer.send_order(order, order.user).deliver_now
      flash[:succes] = 'Pedido gerado com sucesso. ' \
                        "Email enviado para: #{order.user.email}"
      redirect_to root_path
    end
  end
end

app/views/admin/orders/index.html.erb
<% content_for :header_title do %>
  Administrador
<% end %>
<% content_for :page_title do %>
  Pedidos
<% end %>

<section id="orders-filter">
  <div class="row">
    <div class="col-md-12">
      <div class="ls-box ls-box-gray">
        <h3>Filtro</h3>
        <br>
        <div class="ls-group-btn ls-group-active">
          <%= link_to 'Todos', admin_orders_path, class: "ls-btn-primary #{button_active?(nil, @current_filter)}" %>
          <% @statuses.each do |status| %>
            <%= link_to status[:value], admin_orders_path(filter: status[:key]), class: "ls-btn-primary #{button_active?(status[:key], @current_filter)}" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="orders">
  <div class="row">
    <div class="col-md-12">
      <% unless @orders.empty? %>
        <table class="ls-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Produto</th>
              <th>Plano</th>
              <th>Período</th>
              <th>Preço</th>
              <th>Cliente</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= order.id %></td>
                <td><%= order.product %></td>
                <td><%= order.plan %></td>
                <td><%= order.period %></td>
                <td><%= order.price %></td>
                <td><%= order.user.name unless order.user.nil? %></td>
                <td><%= order.status %> </td>
                <td><section id='order<%=order.id%>'>
                    <% if order.opened? %>
                      <%= link_to 'Cancelar', cancel_order_path(order), method: :put, class: 'ls-btn-primary-danger' %>
                    <% else %>
                      <%= link_to 'Visualizar', order_path(order), class: 'ls-btn-primary' %>
                    <% end %>
                  </section></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</section>