config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cart#products'

  namespace :admin do
    resources :orders, only: [:index]
  end

  namespace :customer do
    resources :orders, only: [:index]
  end

  resources :orders, only: [:show, :create] do
    member do
      put 'cancel'
      put 'finish'
      get 'resume'
      get 'checkout'
      put 'coupon'
    end
  end

  #namespace :cart do
  resource :cart, only: [] do
      get 'products', to: 'cart#products'
      get ':product/:product_id/plans', to: 'cart#plans', as: 'product_plans'
      get ':product/:product_id/:plan/:plan_id/prices', to: 'cart#prices', as: 'plan_prices'
  end

  resources :payments, only: [:create]
  resources :sellers, only: [:new, :create]

  namespace :seller do
    get '/:id/checkout', to: 'orders#checkout', as: 'checkout'
    post 'send/order/:id', to: 'orders#send_order', as: 'send_order'
  end

  resources :payments, only: [:create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_menus, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_current_location, unless: :devise_controller?

  def set_menus
    scope = menu_scope

    @left_menu = "left_#{scope}_menu"
    @top_menu = "top_#{scope}_menu"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def redirect_admin
    redirect_to admin_orders_path if user_signed_in? && current_user.admin?
  end

  def menu_scope
    return current_user.role if user_signed_in?
    'visitor'
  end

  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_active?(status, current_status)
    'ls-active' if status == current_status
  end
end

app/views/application/_flash_alert.html.erb
<section id="flash-messages">
  <% flash.each do |key, value| %>
    <div class="ls-alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</section>

app/views/application/_header.html.erb
<div class="ls-topbar ">

  <!-- Barra de Notificações -->
  <div class="ls-notification-topbar">

    <!-- Links de apoio -->
    <div class="ls-alerts-list">
      <%= link_to "http://qsd.campuscode.com.br/projeto_final/vendas", { class:'ls-ico-question', target: '_blank' } do %>
        <span>Projeto</span>
      <% end %>
    </div>

    <!-- Dropdown com detalhes da conta de usuário -->
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <%= render @top_menu %>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <!-- Nome do produto/marca com sidebar -->
  <h1 class="ls-brand-name">
    <%= link_to '#', { class: 'ls-ico-earth' } do %>
      <%= yield :header_title %>
    <% end %>
  </h1>

  <!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
</div>

app/views/application/_left_admin_menu.html.erb
<ul>
  <li>
    <%= link_to 'Início', root_path, class: 'ls-ico-home' %>
  </li>
  <li>
    <%= link_to 'Pedidos', admin_orders_path, class: 'ls-ico-list' %>
  </li>
  <li>
    <%= link_to 'Cadastrar Vendedor', new_seller_path, class: 'ls-ico-user-add' %>
    </li>
</ul>

app/views/application/_left_bar.html.erb
<section id="left-bar">
  <aside class="ls-sidebar">
    <div class="ls-sidebar-inner">
      <nav class="ls-menu">
        <%= render @left_menu %>
      </nav>
    </div>
  </aside>
</section>

app/views/application/_left_customer_menu.html.erb
<ul>
  <li>
    <%= link_to 'Início', root_path, class: 'ls-ico-home' %>
  </li>
  <li>
    <%= link_to 'Produtos', root_path, class: 'ls-ico-dashboard' %>
  </li>
  <li>
    <%= link_to 'Meus Pedidos', customer_orders_path, class: 'ls-ico-list' %>
  </li>
</ul>

app/views/application/_left_seller_menu.html.erb
<ul>
  <li>
    <%= link_to 'Início', root_path, class: 'ls-ico-home' %>
  </li>
  <li>
    <%= link_to 'Produtos', root_path, class: 'ls-ico-dashboard' %>
  </li>
</ul>

app/views/application/_left_visitor_menu.html.erb
<ul>
  <li>
    <%= link_to 'Início', root_path, class: 'ls-ico-home' %>
  </li>
  <li>
    <%= link_to 'Produtos', products_cart_path, class: 'ls-ico-dashboard' %>
  </li>
</ul>

app/views/application/_top_admin_menu.html.erb
<a href="#" class="ls-ico-user">
  <%= image_tag 'avatar.png' %>
  <span class="ls-name"><%= current_user.name %></span>
</a>

<nav class="ls-dropdown-nav ls-user-menu">
  <ul>
    <li><%= link_to t('nav.sign_out'), destroy_user_session_path, method: 'DELETE' %></li>
  </ul>
</nav>

app/views/application/_top_customer_menu.html.erb
<a href="#" class="ls-ico-user">
  <%= image_tag 'avatar.png' %>
  <span class="ls-name"><%= current_user.name %></span>
</a>

<nav class="ls-dropdown-nav ls-user-menu">
  <ul>
    <li><%= link_to t('nav.sign_out'), destroy_user_session_path, method: 'DELETE' %></li>
  </ul>
</nav>

app/views/application/_top_seller_menu.html.erb
<a href="#" class="ls-ico-user">
  <%= image_tag 'avatar.png' %>
  <span class="ls-name"><%= current_user.name %></span>
</a>

<nav class="ls-dropdown-nav ls-user-menu">
  <ul>
    <li><%= link_to t('nav.sign_out'), destroy_user_session_path, method: 'DELETE' %></li>
  </ul>
</nav>

app/views/application/_top_visitor_menu.html.erb
<a href="#" class="ls-ico-user">
  <%= image_tag 'avatar.png' %>
  <span class="ls-name"><%= t('nav.button_account.unlogged')%></span>
</a>

<nav class="ls-dropdown-nav ls-user-menu">
  <ul>
    <li><%= link_to t('nav.sign_in'), new_user_session_path %></li>
    <li><%= link_to t('nav.sign_up'), new_user_registration_path %></li>
  </ul>
</nav>